/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaInterface;

import CapaNegocio.*;
import java.awt.Color;
import javax.swing.JTextField;

/**
 *
 * @author Usuario
 */
public class WinCalculadora extends javax.swing.JFrame {

    /**
     * Creates new form WinCalculadora
     */
    ClsOperaciones a,b,c;
    int tipo,m,n,codigo;
    float r,i;
    public WinCalculadora() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(new Color(111,164,187));
        this.PnlFraccion.setBackground(new Color(111,164,187));
        this.PnlComplejos.setBackground(new Color(111,164,187));
        this.PnlPunto.setBackground(new Color(111,164,187));
        this.OptFraccion.setBackground(new Color(111,164,187));
        this.OptComplejo.setBackground(new Color(111,164,187));
        this.OptPunto.setBackground(new Color(111,164,187));
        PnlPunto.setVisible(false);
        PnlComplejos.setVisible(false);
        PnlFraccion.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        TxtDisplay = new javax.swing.JTextField();
        OptFraccion = new javax.swing.JRadioButton();
        OptComplejo = new javax.swing.JRadioButton();
        OptPunto = new javax.swing.JRadioButton();
        BtnOp1 = new javax.swing.JButton();
        BtnOp2 = new javax.swing.JButton();
        BtnSuma = new javax.swing.JButton();
        BtnResta = new javax.swing.JButton();
        BtnIgual = new javax.swing.JButton();
        BtnLimpiar = new javax.swing.JButton();
        BtnSalir = new javax.swing.JButton();
        btnPor = new javax.swing.JButton();
        BtnPara = new javax.swing.JButton();
        PnlFraccion = new javax.swing.JPanel();
        BtnValor = new javax.swing.JButton();
        BtnSimplificar = new javax.swing.JButton();
        PnlComplejos = new javax.swing.JPanel();
        BtnConjugado = new javax.swing.JButton();
        PnlPunto = new javax.swing.JPanel();
        btnPolar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplicación Calculadora Múltiple usando Interface");

        TxtDisplay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        buttonGroup1.add(OptFraccion);
        OptFraccion.setText("Fracción");
        OptFraccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OptFraccionActionPerformed(evt);
            }
        });

        buttonGroup1.add(OptComplejo);
        OptComplejo.setText("Complejo");
        OptComplejo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OptComplejoActionPerformed(evt);
            }
        });

        buttonGroup1.add(OptPunto);
        OptPunto.setText("Punto");
        OptPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OptPuntoActionPerformed(evt);
            }
        });

        BtnOp1.setText("Operando1");
        BtnOp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOp1ActionPerformed(evt);
            }
        });

        BtnOp2.setText("Operando2");
        BtnOp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOp2ActionPerformed(evt);
            }
        });

        BtnSuma.setText("+");
        BtnSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSumaActionPerformed(evt);
            }
        });

        BtnResta.setText("-");
        BtnResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRestaActionPerformed(evt);
            }
        });

        BtnIgual.setText("Igual");
        BtnIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIgualActionPerformed(evt);
            }
        });

        BtnLimpiar.setText("Limpiar");
        BtnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimpiarActionPerformed(evt);
            }
        });

        BtnSalir.setText("Salir");
        BtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirActionPerformed(evt);
            }
        });

        btnPor.setText("*");
        btnPor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPorActionPerformed(evt);
            }
        });

        BtnPara.setText("/");
        BtnPara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnParaActionPerformed(evt);
            }
        });

        BtnValor.setText("Valor Real");
        BtnValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnValorActionPerformed(evt);
            }
        });

        BtnSimplificar.setText("Simplificar");
        BtnSimplificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSimplificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PnlFraccionLayout = new javax.swing.GroupLayout(PnlFraccion);
        PnlFraccion.setLayout(PnlFraccionLayout);
        PnlFraccionLayout.setHorizontalGroup(
            PnlFraccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlFraccionLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(PnlFraccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BtnValor, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addComponent(BtnSimplificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PnlFraccionLayout.setVerticalGroup(
            PnlFraccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlFraccionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnValor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnSimplificar))
        );

        BtnConjugado.setText("Conjugado");
        BtnConjugado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnConjugadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PnlComplejosLayout = new javax.swing.GroupLayout(PnlComplejos);
        PnlComplejos.setLayout(PnlComplejosLayout);
        PnlComplejosLayout.setHorizontalGroup(
            PnlComplejosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlComplejosLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(BtnConjugado)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        PnlComplejosLayout.setVerticalGroup(
            PnlComplejosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlComplejosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnConjugado))
        );

        btnPolar.setText("Polar");
        btnPolar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPolarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PnlPuntoLayout = new javax.swing.GroupLayout(PnlPunto);
        PnlPunto.setLayout(PnlPuntoLayout);
        PnlPuntoLayout.setHorizontalGroup(
            PnlPuntoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlPuntoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPolar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PnlPuntoLayout.setVerticalGroup(
            PnlPuntoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlPuntoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPolar))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(PnlComplejos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(PnlFraccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(238, 238, 238))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(BtnOp1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnOp2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(143, 143, 143)
                                    .addComponent(OptFraccion)
                                    .addGap(18, 18, 18)
                                    .addComponent(OptComplejo)
                                    .addGap(18, 18, 18)
                                    .addComponent(OptPunto))
                                .addComponent(TxtDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnPor)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(BtnPara))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(BtnSuma)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BtnResta))
                                    .addComponent(BtnIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(141, 141, 141)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(BtnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(PnlPunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(TxtDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OptFraccion)
                    .addComponent(OptComplejo)
                    .addComponent(OptPunto))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnOp1)
                    .addComponent(BtnOp2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnSuma)
                            .addComponent(BtnResta))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPor)
                            .addComponent(BtnPara)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnLimpiar)
                        .addGap(4, 4, 4)
                        .addComponent(BtnSalir)))
                .addGap(18, 18, 18)
                .addComponent(BtnIgual)
                .addGap(18, 18, 18)
                .addComponent(PnlFraccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PnlComplejos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PnlPunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OptFraccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OptFraccionActionPerformed
        BtnOp1.setText("Numerador");
        BtnOp2.setText("Denominador");
        tipo=1;
        TxtDisplay.requestFocus();
        PnlFraccion.setVisible(true);
        PnlComplejos.setVisible(false);
        PnlPunto.setVisible(false);
        
    }//GEN-LAST:event_OptFraccionActionPerformed

    private void OptComplejoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OptComplejoActionPerformed
        BtnOp1.setText("Parte Real");
        BtnOp2.setText("Parte Imaginaria");
        tipo=2;
        TxtDisplay.requestFocus();
        PnlFraccion.setVisible(false);
        PnlComplejos.setVisible(true);
        PnlPunto.setVisible(false);
    }//GEN-LAST:event_OptComplejoActionPerformed

    private void OptPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OptPuntoActionPerformed
        // TODO add your handling code here:
        BtnOp1.setText("Coordenada X");
        BtnOp2.setText("Coordenada Y");
        tipo=3;
        TxtDisplay.requestFocus();
        PnlFraccion.setVisible(false);
        PnlComplejos.setVisible(false);
        PnlPunto.setVisible(true);
    }//GEN-LAST:event_OptPuntoActionPerformed

    private void BtnOp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOp1ActionPerformed
        // TODO add your handling code here:
        r=Float.parseFloat(TxtDisplay.getText());
        TxtDisplay.setText(null);
        TxtDisplay.requestFocus();
    }//GEN-LAST:event_BtnOp1ActionPerformed

    private void BtnOp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOp2ActionPerformed
        // TODO add your handling code here:
        i=Float.parseFloat(TxtDisplay.getText());
        switch(tipo){
            case 1:
            {
                m=(int)i;
                n=(int)r;
                b=new ClsFraccion(n,m);
                break;
            }
            case 2:
            {
                b=new ClsComplejos(r,i);
                break;
            }
            case 3:
            {
                b=new ClsPunto(r,i);
                break;
            }
        }
        TxtDisplay.setText(b.ToString());
        TxtDisplay.requestFocus();
    }//GEN-LAST:event_BtnOp2ActionPerformed

    private void BtnSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSumaActionPerformed
        // TODO add your handling code here:
        TxtDisplay.setText(null);
        a=b;
        TxtDisplay.requestFocus();
        codigo=1;
    }//GEN-LAST:event_BtnSumaActionPerformed

    private void BtnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimpiarActionPerformed
        // TODO add your handling code here:
        TxtDisplay.setText(null);
        TxtDisplay.requestFocus();
    }//GEN-LAST:event_BtnLimpiarActionPerformed

    private void BtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_BtnSalirActionPerformed

    private void BtnRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRestaActionPerformed
        // TODO add your handling code here:
        TxtDisplay.setText(null);
        a=b;
        TxtDisplay.requestFocus();
        codigo=2;
    }//GEN-LAST:event_BtnRestaActionPerformed

    private void btnPorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPorActionPerformed
        // TODO add your handling code here:
        TxtDisplay.setText(null);
        a=b;
        TxtDisplay.requestFocus();
        codigo=3;        
    }//GEN-LAST:event_btnPorActionPerformed

    private void BtnParaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnParaActionPerformed
        // TODO add your handling code here:
        TxtDisplay.setText(null);
        a=b;
        TxtDisplay.requestFocus();
        codigo=4;        
    }//GEN-LAST:event_BtnParaActionPerformed

    private void BtnIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIgualActionPerformed
        // TODO add your handling code here:
        switch(codigo){
            case 1:
            {
                b=(ClsOperaciones)a.mas(b);
                break;
            }
            case 2:
            {
                b=(ClsOperaciones)a.menos(b);
                break;
            }
            case 3:
            {
                b=(ClsOperaciones)a.por(b);
                break;
            }
            case 4:
            {
                b=(ClsOperaciones)a.para(b);
                break;
            }
        }
        TxtDisplay.setText(b.ToString());
        TxtDisplay.requestFocus();
    }//GEN-LAST:event_BtnIgualActionPerformed

    private void BtnValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnValorActionPerformed
        // TODO add your handling code here:
        ClsFraccion B= new ClsFraccion(n,m);
        B= (ClsFraccion)b;
        TxtDisplay.setText(String.valueOf(B.valor()));
    }//GEN-LAST:event_BtnValorActionPerformed

    private void BtnConjugadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnConjugadoActionPerformed
        // TODO add your handling code here:
        
        ClsComplejos B=(ClsComplejos)b;
        ClsComplejos A=B.Conjugado();
        TxtDisplay.setText(A.ToString());
    }//GEN-LAST:event_BtnConjugadoActionPerformed

    private void BtnSimplificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSimplificarActionPerformed
        ClsFraccion B=(ClsFraccion)b;
        B.Simplificar();
        TxtDisplay.setText(B.ToString());
        
    }//GEN-LAST:event_BtnSimplificarActionPerformed

    private void btnPolarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPolarActionPerformed
        // TODO add your handling code here:
        ClsPunto B= (ClsPunto)b;
        TxtDisplay.setText(B.polar());
    }//GEN-LAST:event_btnPolarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WinCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WinCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WinCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WinCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnConjugado;
    private javax.swing.JButton BtnIgual;
    private javax.swing.JButton BtnLimpiar;
    private javax.swing.JButton BtnOp1;
    private javax.swing.JButton BtnOp2;
    private javax.swing.JButton BtnPara;
    private javax.swing.JButton BtnResta;
    private javax.swing.JButton BtnSalir;
    private javax.swing.JButton BtnSimplificar;
    private javax.swing.JButton BtnSuma;
    private javax.swing.JButton BtnValor;
    private javax.swing.JRadioButton OptComplejo;
    private javax.swing.JRadioButton OptFraccion;
    private javax.swing.JRadioButton OptPunto;
    private javax.swing.JPanel PnlComplejos;
    private javax.swing.JPanel PnlFraccion;
    private javax.swing.JPanel PnlPunto;
    private javax.swing.JTextField TxtDisplay;
    private javax.swing.JButton btnPolar;
    private javax.swing.JButton btnPor;
    private javax.swing.ButtonGroup buttonGroup1;
    // End of variables declaration//GEN-END:variables
}
